### ISSUE TITLE
Syntax Error: Unexpected <EOF>

### ISSUE THREAD

**Issue by gns-pkulkarni** [prabhatrawat-webkul/graphql-php#1]
Hi,

I'm running this on Ubuntu XAMPP. My URL is "http://localhost/graphQL/composerGQL.php/" I'm having following error message from catch block. 

**{"errors":[{"message":"Syntax Error: Unexpected <EOF>","extensions":{"category":"graphql"},"locations":[{"line":1,"column":1}]}]}**

I've debugged the code and found that
**$rawInput = file_get_contents('php://input')** // This line gives empty content. $rawInput is NULL.

**composerGQL.php Code**
PHP code files is attached as phpcode.txt

[phpcode.txt](https://github.com/prabhatrawat-webkul/graphql-php/files/3650970/phpcode.txt)
@prabhatrawat-webkul Please Help.

**Comment by prabhatrawat-webkul** [comment]
used your code  its working fine.
http://prntscr.com/q1a1io
please use chromiQl extension,
follow this blog.
https://webkul.com/blog/how-to-use-graphql-in-php/

reason for the error is that you have not passed the query in request.

use this

> {"query":"{\n  customer(id: 1) {\n    id\n    firstname \n    lastname\n  }\n}\n","variables":null,"operationName":null}

**Comment by gns-pkulkarni** [comment]
Okay. Thank you so much
